# docker-compose: 도커 컨테이너 관리
# docker-compose.yml: 개발용으로 사용
# docker-compose-deploy.yml: 배포용으로 사용

version: "3.11"

# docker-compose: 프론트엔드, 백엔드, DB, NginX
services:
  app: # Django
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command: >
      sh -c 'python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000'
    environment:
      - DB_HOST=db
      - DB_NAME=session
      - DB_USER=jinwoo
      - DB_PASS=jinwoo1!
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=session
      - POSTGRES_USER=jinwoo
      - POSTGRES_PASSWORD=jinwoo1!